=== Tachyonite/ModProjectMutagenesis/Schemas/GameDBTreatment.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="enums.xsd" />
    <xs:element name="Database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GameDBTreatment" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="GameDBTreatment">
                                <xs:attribute name="ID" type="xs:string" use="required" />
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="GameDBTreatment">
        <xs:all>
            <xs:element name="AbbreviationLocID" type="xs:string" minOccurs="1" />
            <xs:element name="DiscomfortLevel" type="SymptomHazard" minOccurs="0" />
            <xs:element name="TreatmentType" type="TreatmentType" minOccurs="0" />
            <xs:element name="ReceiptType" type="ReceiptType" minOccurs="0" />
            <xs:element name="Procedure" type="GameDBProcedure" minOccurs="0" />
            <xs:element name="DurationHours" type="xs:float" minOccurs="0" />
            <xs:element name="HospitalizationTreatmentRef" type="xs:string" minOccurs="0" />
            <xs:element name="AllowedWithAnyHospitalization" type="xs:boolean" minOccurs="0" />
            <xs:element name="IconIndex" type="xs:positiveInteger" minOccurs="0" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="GameDBProcedure">
        <xs:all>
            <xs:element name="DressLevel" type="DressLevel" minOccurs="0" />
            <xs:element name="DressLevelAfter" type="DressLevel" minOccurs="0" />
            <xs:element name="StaffSelectionRules" type="StaffSelectionRules" minOccurs="0" />
            <xs:element name="RequiredIndistinctEmployeeCount" type="xs:int" minOccurs="0" />
            <xs:element name="Biohazard" type="xs:boolean" minOccurs="0" />
            <xs:element name="ProcedureScript" type="xs:string" minOccurs="1" />
            <xs:element name="AnimationSetupSitting" type="AnimationSetup" minOccurs="0" />

            <xs:element name="RequiredSkillsToPrescribe" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SkillRef" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="RequiredDoctorQualificationList" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SkillRef" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="RequiredRoomTags" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Tag" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="GameDBProcedureComplication">
        <xs:all>
            <xs:element name="SymptomRef" type="xs:string" minOccurs="1" />
            <xs:element name="StartTimeHours" type="xs:int" />
            <xs:element name="ProbabilityPercent" type="xs:int" />
            <xs:element name="ProbabilityPercentMaxSkillLevel" />
        </xs:all>
    </xs:complexType>
    <xs:complexType name="AnimationSetup">
        <xs:all>
            <xs:element name="AnimationNameIn" type="xs:string" />
            <xs:element name="AnimationNameIdle" type="xs:string" />
            <xs:element name="AnimationNameOut" type="xs:string" />
        </xs:all>
    </xs:complexType>
</xs:schema>

=== Tachyonite/ModProjectMutagenesis/Database/ModProcedures/DebugProcedure.xml
<Database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Schemas/GameDBTreatment.xsd">
    <GameDBTreatment ID="MUT_DBG_TRT_TEST_PROCEDURE">
        <AbbreviationLocID>MUT_DBG_TRT_TEST_PROCEDURE</AbbreviationLocID>
        <DiscomfortLevel>Medium</DiscomfortLevel>
        <Procedure>
            <StaffSelectionRules>REQUIRED_ROOM_OR_DEFAULT_ROOM</StaffSelectionRules>

            <RequiredSkillsToPrescribe>
                <SkillRef>SKILL_DOC_SPEC_GENERAL_SURGERY</SkillRef>
                <SkillRef>SKILL_DOC_SPEC_INTERNAL_MEDICINE</SkillRef>
                <SkillRef>SKILL_DOC_SPEC_CRITICAL_CARE</SkillRef>
            </RequiredSkillsToPrescribe>

            <RequiredDoctorQualificationList>
                <SkillRef>SKILL_DOC_SPEC_GENERAL_SURGERY</SkillRef>
                <SkillRef>SKILL_DOC_SPEC_INTERNAL_MEDICINE</SkillRef>
                <SkillRef>SKILL_DOC_SPEC_CRITICAL_CARE</SkillRef>
            </RequiredDoctorQualificationList>

            <!--RequiredRoomTypeList>
                <RequiredRoomTypeRef>ROOM_TYPE_INTENSIVE_CARE_UNIT</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_INPATIENT_WARD</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_HIGH_PRIORITY_INPATIENT_WARD</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_GENERAL_SURGERY_OFFICE</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_INPATIENT_GS_OFFICE</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_INTERNAL_MEDICINE_OFFICE</RequiredRoomTypeRef>
                <RequiredRoomTypeRef>ROOM_TYPE_INPATIENT_IM_OFFICE</RequiredRoomTypeRef>
            </RequiredRoomTypeList-->
            <RequiredRoomTags>
                <Tag>general_surgery_office</Tag>
                <Tag>internal_medicine_office</Tag>
                <Tag>icu</Tag>
                <!-- receipt - automatically done in on-call room for other hospitalizations than observation -->
            </RequiredRoomTags>

            <ProcedureScript>ProjectMutagenesis.DebugScripts.TestProcedure</ProcedureScript>
            <!--TODO tempAnim is anim here needed at all? keep temp for now -->
            <AnimationSetupSitting>
                <AnimationNameIn>stand_press_bandage_hand_in</AnimationNameIn>
                <AnimationNameIdle>stand_press_bandage_hand_idle</AnimationNameIdle>
                <AnimationNameOut>stand_press_bandage_hand_out</AnimationNameOut>
            </AnimationSetupSitting>
            <DressLevel>FULL</DressLevel>
            <DressLevelAfter>FULL</DressLevelAfter>
        </Procedure>
        <TreatmentType>RECEIPT</TreatmentType>
        <ReceiptType>IV_BAG</ReceiptType>
        <IconIndex>1951</IconIndex>
        <DurationHours>0</DurationHours>
        <HospitalizationTreatmentRef>TRT_HOSPITALIZATION_NORMAL</HospitalizationTreatmentRef>
        <AllowedWithAnyHospitalization>true</AllowedWithAnyHospitalization>
    </GameDBTreatment>
</Database>
